ALTER TABLE incident_telemetry
    ADD COLUMN IF NOT EXISTS distance_m DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS respect_score INTEGER,
    ADD COLUMN IF NOT EXISTS screen_active BOOLEAN,
    ADD COLUMN IF NOT EXISTS mode_confidence DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS source VARCHAR(24) DEFAULT 'in_app',
    ADD COLUMN IF NOT EXISTS city VARCHAR(80) DEFAULT 'Vitoria',
    ADD COLUMN IF NOT EXISTS features_json TEXT;
